[2024-12-03T12:13:10.960+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T12:13:10.970+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_and_upload_json_to_hdfs.run_make_model scheduled__2024-12-03T02:00:00+00:00 [queued]>
[2024-12-03T12:13:10.977+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_and_upload_json_to_hdfs.run_make_model scheduled__2024-12-03T02:00:00+00:00 [queued]>
[2024-12-03T12:13:10.977+0900] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-03T12:13:10.994+0900] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_make_model> on 2024-12-03 02:00:00+00:00
[2024-12-03T12:13:10.997+0900] {standard_task_runner.py:72} INFO - Started process 328077 to run task
[2024-12-03T12:13:11.000+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'process_and_upload_json_to_hdfs', 'run_make_model', 'scheduled__2024-12-03T02:00:00+00:00', '--job-id', '445', '--raw', '--subdir', 'DAGS_FOLDER/data_to_hdfs.py', '--cfg-path', '/tmp/tmpiwz1aad7']
[2024-12-03T12:13:11.002+0900] {standard_task_runner.py:105} INFO - Job 445: Subtask run_make_model
[2024-12-03T12:13:11.035+0900] {task_command.py:467} INFO - Running <TaskInstance: process_and_upload_json_to_hdfs.run_make_model scheduled__2024-12-03T02:00:00+00:00 [running]> on host MN
[2024-12-03T12:13:11.098+0900] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='process_and_upload_json_to_hdfs' AIRFLOW_CTX_TASK_ID='run_make_model' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-03T02:00:00+00:00'
[2024-12-03T12:13:11.098+0900] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T12:13:11.112+0900] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-03T12:13:11.113+0900] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '/laewon/spark/bin/spark-submit --master yarn --deploy-mode cluster /laewon/Riot/make_model.py']
[2024-12-03T12:13:11.119+0900] {subprocess.py:99} INFO - Output:
[2024-12-03T12:13:13.373+0900] {subprocess.py:106} INFO - 24/12/03 12:13:13 INFO DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at MN/192.168.4.7:8032
[2024-12-03T12:13:14.062+0900] {subprocess.py:106} INFO - 24/12/03 12:13:14 INFO Configuration: resource-types.xml not found
[2024-12-03T12:13:14.062+0900] {subprocess.py:106} INFO - 24/12/03 12:13:14 INFO ResourceUtils: Unable to find 'resource-types.xml'.
[2024-12-03T12:13:14.077+0900] {subprocess.py:106} INFO - 24/12/03 12:13:14 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (819200 MB per container)
[2024-12-03T12:13:14.078+0900] {subprocess.py:106} INFO - 24/12/03 12:13:14 INFO Client: Will allocate AM container, with 1408 MB memory including 384 MB overhead
[2024-12-03T12:13:14.078+0900] {subprocess.py:106} INFO - 24/12/03 12:13:14 INFO Client: Setting up container launch context for our AM
[2024-12-03T12:13:14.082+0900] {subprocess.py:106} INFO - 24/12/03 12:13:14 INFO Client: Setting up the launch environment for our AM container
[2024-12-03T12:13:14.094+0900] {subprocess.py:106} INFO - 24/12/03 12:13:14 INFO Client: Preparing resources for our AM container
[2024-12-03T12:13:14.129+0900] {subprocess.py:106} INFO - 24/12/03 12:13:14 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
[2024-12-03T12:13:16.966+0900] {subprocess.py:106} INFO - 24/12/03 12:13:16 INFO Client: Uploading resource file:/tmp/spark-77c06ed0-e836-49f4-9a84-88e67d7003eb/__spark_libs__17301168484888003263.zip -> hdfs://MN:9000/user/dke/.sparkStaging/application_1733127595631_0023/__spark_libs__17301168484888003263.zip
[2024-12-03T12:13:49.473+0900] {subprocess.py:106} INFO - 24/12/03 12:13:49 INFO Client: Uploading resource file:/laewon/Riot/make_model.py -> hdfs://MN:9000/user/dke/.sparkStaging/application_1733127595631_0023/make_model.py
[2024-12-03T12:13:49.510+0900] {subprocess.py:106} INFO - 24/12/03 12:13:49 INFO Client: Uploading resource file:/laewon/spark-3.5.1-bin-hadoop3/python/lib/pyspark.zip -> hdfs://MN:9000/user/dke/.sparkStaging/application_1733127595631_0023/pyspark.zip
[2024-12-03T12:13:49.761+0900] {subprocess.py:106} INFO - 24/12/03 12:13:49 INFO Client: Uploading resource file:/laewon/spark-3.5.1-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip -> hdfs://MN:9000/user/dke/.sparkStaging/application_1733127595631_0023/py4j-0.10.9.7-src.zip
[2024-12-03T12:13:49.966+0900] {subprocess.py:106} INFO - 24/12/03 12:13:49 INFO Client: Uploading resource file:/tmp/spark-77c06ed0-e836-49f4-9a84-88e67d7003eb/__spark_conf__1265222114602429913.zip -> hdfs://MN:9000/user/dke/.sparkStaging/application_1733127595631_0023/__spark_conf__.zip
[2024-12-03T12:13:50.044+0900] {subprocess.py:106} INFO - 24/12/03 12:13:50 INFO SecurityManager: Changing view acls to: dke
[2024-12-03T12:13:50.044+0900] {subprocess.py:106} INFO - 24/12/03 12:13:50 INFO SecurityManager: Changing modify acls to: dke
[2024-12-03T12:13:50.045+0900] {subprocess.py:106} INFO - 24/12/03 12:13:50 INFO SecurityManager: Changing view acls groups to:
[2024-12-03T12:13:50.045+0900] {subprocess.py:106} INFO - 24/12/03 12:13:50 INFO SecurityManager: Changing modify acls groups to:
[2024-12-03T12:13:50.045+0900] {subprocess.py:106} INFO - 24/12/03 12:13:50 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: dke; groups with view permissions: EMPTY; users with modify permissions: dke; groups with modify permissions: EMPTY
[2024-12-03T12:13:50.085+0900] {subprocess.py:106} INFO - 24/12/03 12:13:50 INFO Client: Submitting application application_1733127595631_0023 to ResourceManager
[2024-12-03T12:13:50.134+0900] {subprocess.py:106} INFO - 24/12/03 12:13:50 INFO YarnClientImpl: Submitted application application_1733127595631_0023
[2024-12-03T12:13:51.137+0900] {subprocess.py:106} INFO - 24/12/03 12:13:51 INFO Client: Application report for application_1733127595631_0023 (state: ACCEPTED)
[2024-12-03T12:13:51.140+0900] {subprocess.py:106} INFO - 24/12/03 12:13:51 INFO Client:
[2024-12-03T12:13:51.141+0900] {subprocess.py:106} INFO - 	 client token: N/A
[2024-12-03T12:13:51.141+0900] {subprocess.py:106} INFO - 	 diagnostics: AM container is launched, waiting for AM container to Register with RM
[2024-12-03T12:13:51.141+0900] {subprocess.py:106} INFO - 	 ApplicationMaster host: N/A
[2024-12-03T12:13:51.142+0900] {subprocess.py:106} INFO - 	 ApplicationMaster RPC port: -1
[2024-12-03T12:13:51.142+0900] {subprocess.py:106} INFO - 	 queue: root.default
[2024-12-03T12:13:51.142+0900] {subprocess.py:106} INFO - 	 start time: 1733195630110
[2024-12-03T12:13:51.142+0900] {subprocess.py:106} INFO - 	 final status: UNDEFINED
[2024-12-03T12:13:51.142+0900] {subprocess.py:106} INFO - 	 tracking URL: http://MN:8088/proxy/application_1733127595631_0023/
[2024-12-03T12:13:51.143+0900] {subprocess.py:106} INFO - 	 user: dke
[2024-12-03T12:13:58.149+0900] {subprocess.py:106} INFO - 24/12/03 12:13:58 INFO Client: Application report for application_1733127595631_0023 (state: RUNNING)
[2024-12-03T12:13:58.150+0900] {subprocess.py:106} INFO - 24/12/03 12:13:58 INFO Client:
[2024-12-03T12:13:58.150+0900] {subprocess.py:106} INFO - 	 client token: N/A
[2024-12-03T12:13:58.151+0900] {subprocess.py:106} INFO - 	 diagnostics: N/A
[2024-12-03T12:13:58.151+0900] {subprocess.py:106} INFO - 	 ApplicationMaster host: SN04
[2024-12-03T12:13:58.151+0900] {subprocess.py:106} INFO - 	 ApplicationMaster RPC port: 37279
[2024-12-03T12:13:58.151+0900] {subprocess.py:106} INFO - 	 queue: root.default
[2024-12-03T12:13:58.152+0900] {subprocess.py:106} INFO - 	 start time: 1733195630110
[2024-12-03T12:13:58.152+0900] {subprocess.py:106} INFO - 	 final status: UNDEFINED
[2024-12-03T12:13:58.152+0900] {subprocess.py:106} INFO - 	 tracking URL: http://MN:8088/proxy/application_1733127595631_0023/
[2024-12-03T12:13:58.152+0900] {subprocess.py:106} INFO - 	 user: dke
[2024-12-03T12:14:28.189+0900] {subprocess.py:106} INFO - 24/12/03 12:14:28 INFO Client: Application report for application_1733127595631_0023 (state: RUNNING)
[2024-12-03T12:14:32.195+0900] {subprocess.py:106} INFO - 24/12/03 12:14:32 INFO Client: Application report for application_1733127595631_0023 (state: ACCEPTED)
[2024-12-03T12:14:32.195+0900] {subprocess.py:106} INFO - 24/12/03 12:14:32 INFO Client:
[2024-12-03T12:14:32.196+0900] {subprocess.py:106} INFO - 	 client token: N/A
[2024-12-03T12:14:32.196+0900] {subprocess.py:106} INFO - 	 diagnostics: AM container is launched, waiting for AM container to Register with RM
[2024-12-03T12:14:32.196+0900] {subprocess.py:106} INFO - 	 ApplicationMaster host: N/A
[2024-12-03T12:14:32.196+0900] {subprocess.py:106} INFO - 	 ApplicationMaster RPC port: -1
[2024-12-03T12:14:32.197+0900] {subprocess.py:106} INFO - 	 queue: root.default
[2024-12-03T12:14:32.197+0900] {subprocess.py:106} INFO - 	 start time: 1733195630110
[2024-12-03T12:14:32.197+0900] {subprocess.py:106} INFO - 	 final status: UNDEFINED
[2024-12-03T12:14:32.197+0900] {subprocess.py:106} INFO - 	 tracking URL: http://MN:8088/proxy/application_1733127595631_0023/
[2024-12-03T12:14:32.197+0900] {subprocess.py:106} INFO - 	 user: dke
[2024-12-03T12:14:39.204+0900] {subprocess.py:106} INFO - 24/12/03 12:14:39 INFO Client: Application report for application_1733127595631_0023 (state: RUNNING)
[2024-12-03T12:14:39.205+0900] {subprocess.py:106} INFO - 24/12/03 12:14:39 INFO Client:
[2024-12-03T12:14:39.205+0900] {subprocess.py:106} INFO - 	 client token: N/A
[2024-12-03T12:14:39.205+0900] {subprocess.py:106} INFO - 	 diagnostics: N/A
[2024-12-03T12:14:39.205+0900] {subprocess.py:106} INFO - 	 ApplicationMaster host: SN06
[2024-12-03T12:14:39.206+0900] {subprocess.py:106} INFO - 	 ApplicationMaster RPC port: 37205
[2024-12-03T12:14:39.206+0900] {subprocess.py:106} INFO - 	 queue: root.default
[2024-12-03T12:14:39.206+0900] {subprocess.py:106} INFO - 	 start time: 1733195630110
[2024-12-03T12:14:39.206+0900] {subprocess.py:106} INFO - 	 final status: UNDEFINED
[2024-12-03T12:14:39.207+0900] {subprocess.py:106} INFO - 	 tracking URL: http://MN:8088/proxy/application_1733127595631_0023/
[2024-12-03T12:14:39.207+0900] {subprocess.py:106} INFO - 	 user: dke
[2024-12-03T12:14:50.218+0900] {subprocess.py:106} INFO - 24/12/03 12:14:50 INFO Client: Application report for application_1733127595631_0023 (state: FINISHED)
[2024-12-03T12:14:50.218+0900] {subprocess.py:106} INFO - 24/12/03 12:14:50 INFO Client:
[2024-12-03T12:14:50.219+0900] {subprocess.py:106} INFO - 	 client token: N/A
[2024-12-03T12:14:50.219+0900] {subprocess.py:106} INFO - 	 diagnostics: User application exited with status 1
[2024-12-03T12:14:50.219+0900] {subprocess.py:106} INFO - 	 ApplicationMaster host: SN06
[2024-12-03T12:14:50.219+0900] {subprocess.py:106} INFO - 	 ApplicationMaster RPC port: 37205
[2024-12-03T12:14:50.220+0900] {subprocess.py:106} INFO - 	 queue: root.default
[2024-12-03T12:14:50.220+0900] {subprocess.py:106} INFO - 	 start time: 1733195630110
[2024-12-03T12:14:50.220+0900] {subprocess.py:106} INFO - 	 final status: FAILED
[2024-12-03T12:14:50.220+0900] {subprocess.py:106} INFO - 	 tracking URL: http://MN:8088/proxy/application_1733127595631_0023/
[2024-12-03T12:14:50.220+0900] {subprocess.py:106} INFO - 	 user: dke
[2024-12-03T12:14:50.225+0900] {subprocess.py:106} INFO - 24/12/03 12:14:50 ERROR Client: Application diagnostics message: User application exited with status 1
[2024-12-03T12:14:50.227+0900] {subprocess.py:106} INFO - Exception in thread "main" org.apache.spark.SparkException: Application application_1733127595631_0023 finished with failed status
[2024-12-03T12:14:50.227+0900] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1309)
[2024-12-03T12:14:50.227+0900] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1742)
[2024-12-03T12:14:50.227+0900] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
[2024-12-03T12:14:50.228+0900] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-12-03T12:14:50.228+0900] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2024-12-03T12:14:50.228+0900] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-12-03T12:14:50.229+0900] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-12-03T12:14:50.229+0900] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-12-03T12:14:50.229+0900] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-12-03T12:14:50.230+0900] {subprocess.py:106} INFO - 24/12/03 12:14:50 INFO ShutdownHookManager: Shutdown hook called
[2024-12-03T12:14:50.231+0900] {subprocess.py:106} INFO - 24/12/03 12:14:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-77c06ed0-e836-49f4-9a84-88e67d7003eb
[2024-12-03T12:14:50.234+0900] {subprocess.py:106} INFO - 24/12/03 12:14:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-e5369021-983f-4fd0-a953-ff9265ea3a5f
[2024-12-03T12:14:50.587+0900] {subprocess.py:110} INFO - Command exited with return code 1
[2024-12-03T12:14:50.596+0900] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-03T12:14:50.600+0900] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=process_and_upload_json_to_hdfs, task_id=run_make_model, run_id=scheduled__2024-12-03T02:00:00+00:00, execution_date=20241203T020000, start_date=20241203T031310, end_date=20241203T031450
[2024-12-03T12:14:50.616+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T12:14:50.616+0900] {standard_task_runner.py:124} ERROR - Failed to execute job 445 for task run_make_model (Bash command failed. The command returned a non-zero exit code 1.; 328077)
Traceback (most recent call last):
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-03T12:14:50.660+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-03T12:14:50.671+0900] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T12:14:50.672+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
